{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "MTGAI_Python.ipynb",
      "provenance": [],
      "collapsed_sections": []
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    },
    "accelerator": "GPU"
  },
  "cells": [
    {
      "cell_type": "code",
      "metadata": {
        "id": "sbaEpSshLyHq"
      },
      "source": [
        "import numpy as np\n",
        "import pandas as pd\n",
        "\n",
        "import tensorflow as tf\n",
        "from tensorflow import keras\n",
        "from tensorflow.keras import layers\n",
        "\n",
        "import gym\n",
        "from gym import spaces #this adds space.Tuple, and presumably other things as well\n",
        "import random\n",
        "\n"
      ],
      "execution_count": 10,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "x3ZMX-AZuLCU"
      },
      "source": [
        "# 19, 13, 3, 0, 0, 0, 25 for 3 turns\n",
        "# 14, 14, 8, 0, 0, 0, 24 for 4 turns\n",
        "# 8, 14, 10, 3, 0, 0, 25 for 5 turns\n",
        "# 4, 13, 10, 6, 1, 0, 27 for 6 turns\n",
        "# 0, 12, 10, 7, 4, 0, 27 for 7 turns\n",
        "# 0, 10, 10, 7, 5, 1, 27 for 8 turns\n",
        "DECK_CONTENTS = (4, 13, 10, 6, 1, 0, 27)\n",
        "FINAL_TURN = 6\n",
        "\n",
        "\n",
        "class MTGEnv(gym.Env):\n",
        "\n",
        "    def __init__(self):\n",
        "        #check out spaces.MultiDiscrete(), and see if it fits the situation better\n",
        "        #self.observation_space = gym.spaces.Tuple(6)  # Number of state information numbers that need to be provided\n",
        "        ##should provide... (as explaination, '\\' is line countinuation character I believe, and ## are commented out comments so you can remove # from each line)\n",
        "        \n",
        "        ##game state values, Five total, maybe add if a land was played, but currently looks like land automatically played once per turn.\n",
        "        ##limits are FINAL_TURN+1 for turn, FINAL_TURN for ManaLeft, Assume (FINAL_TURN+2)*(FINAL_TURN+2)is limit for CreatureDamage,\n",
        "        ##and that previous number is squared for total damage\n",
        "        #[Turn, ManaLeft, LandsInPlay, CreatureDamage, TotalDamage, \\\n",
        "        \n",
        "        ##This is the hand values which is in order of, 1s, 2s,3s,4s,5s,6s, and lands I believe, and has 7 total values, can probably limit to 7 of each type\n",
        "        ##but will have to have a lose if they can't play anything due to only having one type of non-land in hand, and exceeds the value limit I would guess\n",
        "        #self.hand[0], self.hand[1], self.hand[2], self.hand[3], self.hand[4], self.hand[5], self.hand[6], \\\n",
        "        \n",
        "        ##We also add in the deck states, which also has Seven total values, which can each be from 0 to 53 in general\n",
        "        #self.deck.NumberOf1Cost, \\\n",
        "        #self.deck.NumberOf2Cost, \\\n",
        "        #self.deck.NumberOf3Cost, \\\n",
        "        #self.deck.NumberOf4Cost, \\\n",
        "        #self.deck.NumberOf5Cost, \\\n",
        "        #self.deck.NumberOf6Cost, \\\n",
        "        #self.deck.NumberOfLands) #and this is ending the things we are putting in.  As such, there are 5+7+7 variables for the states.\n",
        "        self.action_space = gym.spaces.Discrete(7)  # Number of possible actions\n",
        "        self.deck = Deck()\n",
        "        self.deck.SetDeck(DECK_CONTENTS[0], DECK_CONTENTS[1], DECK_CONTENTS[2], DECK_CONTENTS[3],\n",
        "                          DECK_CONTENTS[4], DECK_CONTENTS[5], DECK_CONTENTS[6])\n",
        "        hand_arr = self.deck.DrawHand()\n",
        "        self.hand = Hand()\n",
        "        self.hand.SetHand(hand_arr[0], hand_arr[1], hand_arr[2], hand_arr[3],\n",
        "                          hand_arr[4], hand_arr[5], hand_arr[6])\n",
        "        self.FinalTurn = FINAL_TURN\n",
        "        self.Turn = 1\n",
        "        if (self.hand.PlayCard(7)):\n",
        "            self.LandsInPlay = 1\n",
        "            self.ManaLeft = 1\n",
        "        else:\n",
        "            self.LandsInPlay = 0\n",
        "            self.ManaLeft = 1\n",
        "        #self.ManaLeft = LandsInPlay\n",
        "        \n",
        "        self.CreatureDamage = 0\n",
        "        self.TotalDamage = 0\n",
        "        self.CreaturesPlayedThisTurn = [0, 0, 0, 0, 0, 0]\n",
        "        \n",
        "        handInfo = self.hand.GetHand()\n",
        "        \n",
        "        state = np.reshape(np.array([self.Turn, self.ManaLeft, self.LandsInPlay, self.CreatureDamage, self.TotalDamage, \\\n",
        "        handInfo[0], handInfo[1], handInfo[2], handInfo[3], handInfo[4], handInfo[5], handInfo[6], \\\n",
        "        self.deck.NumberOf1Cost, \\\n",
        "        self.deck.NumberOf2Cost, \\\n",
        "        self.deck.NumberOf3Cost, \\\n",
        "        self.deck.NumberOf4Cost, \\\n",
        "        self.deck.NumberOf5Cost, \\\n",
        "        self.deck.NumberOf6Cost, \\\n",
        "        self.deck.NumberOfLands]), (1,19))\n",
        "        done = False\n",
        "        self.reward = 0\n",
        "        info = state\n",
        "        self.pastCreature = 0\n",
        "\n",
        "    def step(self, action):\n",
        "        # Take in the AI's action for one turn, process the results,\n",
        "        # and return the game state information,\n",
        "        # a reward number,\n",
        "        # a value that is True if the game is over and False otherwise,\n",
        "        # and some debugging information.\n",
        "\n",
        "        # Action 0: Pass turn (then play a land if applicable).\n",
        "        # Action 1-6: Play a 1-6 drop creature, do not pass turn\n",
        "\n",
        "        done = False\n",
        "        reward = 0\n",
        "\n",
        "        #commented out before first turn code, and replaced this code in the openai gym init() and reset(), to prevent doing it multiple times in a turn\n",
        "        # Done before the first turn\n",
        "        #if (self.Turn == 1) and (self.hand.NumberOfLands > 0):\n",
        "        #    # Play a land first thing\n",
        "        #    self.hand.PlayCard(7)\n",
        "        #    self.LandsInPlay += 1\n",
        "        #    # Tap all lands, add mana accordingly\n",
        "        #    self.ManaLeft = self.LandsInPlay\n",
        "\n",
        "        # Actions 1-6 are done during the First Main Phase part 2\n",
        "        #Maybe have no punishment, but set done = True, and the reward will return either 0 for not done, or TotalDamage if done.\n",
        "        if action == 1:\n",
        "            if (self.ManaLeft < 1) or (self.hand.NumberOf1Cost < 1):\n",
        "                # Invalid move, punish AI, end game\n",
        "                reward = -100\n",
        "                done = True\n",
        "            else:\n",
        "                self.hand.PlayCard(1)\n",
        "                self.CreaturesPlayedThisTurn[0] += 1\n",
        "                self.ManaLeft -= 1\n",
        "        elif action == 2:\n",
        "            if (self.ManaLeft < 2) or (self.hand.NumberOf2Cost < 1):\n",
        "                # Invalid move, punish AI, end game\n",
        "                reward = -100\n",
        "                done = True\n",
        "            else:\n",
        "                self.hand.PlayCard(2)\n",
        "                self.CreaturesPlayedThisTurn[1] += 1\n",
        "                self.ManaLeft -= 2\n",
        "        elif action == 3:\n",
        "            if (self.ManaLeft < 3) or (self.hand.NumberOf3Cost < 1):\n",
        "                # Invalid move, punish AI, end game\n",
        "                reward = -100\n",
        "                done = True\n",
        "            else:\n",
        "                self.hand.PlayCard(3)\n",
        "                self.CreaturesPlayedThisTurn[2] += 1\n",
        "                self.ManaLeft -= 3\n",
        "        elif action == 4:\n",
        "            if (self.ManaLeft < 4) or (self.hand.NumberOf4Cost < 1):\n",
        "                # Invalid move, punish AI, end game\n",
        "                reward = -100\n",
        "                done = True\n",
        "            else:\n",
        "                self.hand.PlayCard(4)\n",
        "                self.CreaturesPlayedThisTurn[3] += 1\n",
        "                self.ManaLeft -= 4\n",
        "        elif action == 5:\n",
        "            if (self.ManaLeft < 5) or (self.hand.NumberOf5Cost < 1):\n",
        "                # Invalid move, punish AI, end game\n",
        "                reward = -100\n",
        "                done = True\n",
        "            else:\n",
        "                self.hand.PlayCard(5)\n",
        "                self.CreaturesPlayedThisTurn[4] += 1\n",
        "                self.ManaLeft -= 5\n",
        "        elif action == 6:\n",
        "            if (self.ManaLeft < 6) or (self.hand.NumberOf6Cost < 1):\n",
        "                # Invalid move, punish AI, end game\n",
        "                reward = -100\n",
        "                done = True\n",
        "            else:\n",
        "                self.hand.PlayCard(6)\n",
        "                self.CreaturesPlayedThisTurn[5] += 1\n",
        "                self.ManaLeft -= 6\n",
        "        else:  # action == 7\n",
        "            # Begin post-Main Phase actions because AI wants to pass turn\n",
        "            # Combat Phase\n",
        "            self.TotalDamage += self.CreatureDamage\n",
        "\n",
        "            # Ending Phase\n",
        "            # TODO discard down to 7 cards in hand if above 7 cards in hand\n",
        "            if self.Turn == self.FinalTurn:\n",
        "                done = True\n",
        "                reward = self.CreatureDamage\n",
        "            self.Turn += 1\n",
        "            self.hand.AddDrawnCard(self.deck.DrawCard())\n",
        "            # Main Phase part 1\n",
        "            if (self.hand.PlayCard(7)):\n",
        "              self.LandsInPlay += 1\n",
        "            # Tap all lands, add mana accordingly\n",
        "            self.ManaLeft = self.LandsInPlay\n",
        "        self.pastCreature = self.CreatureDamage\n",
        "        # Update total creature damage based on creatures played last turn\n",
        "        for creature_type, played_creature_amt in enumerate(self.CreaturesPlayedThisTurn):\n",
        "            self.CreatureDamage += played_creature_amt * (creature_type + 2)\n",
        "            self.CreaturesPlayedThisTurn[creature_type] = 0\n",
        "\n",
        "        # TODO check what state values the AI should know\n",
        "        #refer to around line 22 for values for state\n",
        "        \n",
        "        handInfo = self.hand.GetHand()\n",
        "        \n",
        "        state = np.reshape(np.array([self.Turn, self.ManaLeft, self.LandsInPlay, self.CreatureDamage, self.TotalDamage, \\\n",
        "        handInfo[0], handInfo[1], handInfo[2], handInfo[3], handInfo[4], handInfo[5], handInfo[6], \\\n",
        "        self.deck.NumberOf1Cost, \\\n",
        "        self.deck.NumberOf2Cost, \\\n",
        "        self.deck.NumberOf3Cost, \\\n",
        "        self.deck.NumberOf4Cost, \\\n",
        "        self.deck.NumberOf5Cost, \\\n",
        "        self.deck.NumberOf6Cost, \\\n",
        "        self.deck.NumberOfLands]), (1,19))\n",
        "        #state = (self.CreatureDamage, self.Turn, self.hand, self.ManaLeft, self.CreaturesPlayedThisTurn, DECK_CONTENTS)\n",
        "        #if not done:\n",
        "        if reward != -100:\n",
        "            reward = self.CreatureDamage - self.pastCreature\n",
        "        info = state\n",
        "        return state, reward, done, info\n",
        "\n",
        "    def reset(self):\n",
        "        # Reset the game for the next iteration.\n",
        "        # Returns the game state information.\n",
        "        self.deck.SetDeck(DECK_CONTENTS[0], DECK_CONTENTS[1], DECK_CONTENTS[2], DECK_CONTENTS[3],\n",
        "                          DECK_CONTENTS[4], DECK_CONTENTS[5], DECK_CONTENTS[6])\n",
        "        hand_arr = self.deck.DrawHand()\n",
        "        self.hand.SetHand(hand_arr[0], hand_arr[1], hand_arr[2], hand_arr[3],\n",
        "                          hand_arr[4], hand_arr[5], hand_arr[6])\n",
        "        self.Turn = 1\n",
        "        #attempt to play the card\n",
        "        if (self.hand.PlayCard(7)):\n",
        "            self.LandsInPlay = 1\n",
        "        else:\n",
        "            self.LandsInPlay = 0\n",
        "        self.ManaLeft = self.LandsInPlay\n",
        "        self.CreatureDamage = 0\n",
        "        self.pastCreature = 0\n",
        "        self.TotalDamage = 0\n",
        "        self.CreaturesPlayedThisTurn = [0, 0, 0, 0, 0, 0]\n",
        "        # TODO check what state values the AI should know, and remember to do in order\n",
        "        \n",
        "        handInfo = self.hand.GetHand()\n",
        "        \n",
        "        state = np.reshape(np.array([self.Turn, self.ManaLeft, self.LandsInPlay, self.CreatureDamage, self.TotalDamage, \\\n",
        "        handInfo[0], handInfo[1], handInfo[2], handInfo[3], handInfo[4], handInfo[5], handInfo[6], \\\n",
        "        self.deck.NumberOf1Cost, \\\n",
        "        self.deck.NumberOf2Cost, \\\n",
        "        self.deck.NumberOf3Cost, \\\n",
        "        self.deck.NumberOf4Cost, \\\n",
        "        self.deck.NumberOf5Cost, \\\n",
        "        self.deck.NumberOf6Cost, \\\n",
        "        self.deck.NumberOfLands]), (1,19))\n",
        "        reward = 0\n",
        "        done = False\n",
        "        info = state\n",
        "        #state = (self.CreatureDamage, self.Turn, self.hand, self.ManaLeft, self.CreaturesPlayedThisTurn, DECK_CONTENTS)\n",
        "        return state\n",
        "\n",
        "    def render(self, mode='human'):\n",
        "        pass\n"
      ],
      "execution_count": 11,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "1pqllLveuewC"
      },
      "source": [
        "class Hand:\n",
        "    def __init__(self):\n",
        "        self.NumberOf1Cost = 0\n",
        "        self.NumberOf2Cost = 0\n",
        "        self.NumberOf3Cost = 0\n",
        "        self.NumberOf4Cost = 0\n",
        "        self.NumberOf5Cost = 0\n",
        "        self.NumberOf6Cost = 0\n",
        "        self.NumberOfLands = 0\n",
        "\n",
        "    def GetHand(self):\n",
        "        return [self.NumberOf1Cost, self.NumberOf2Cost, self.NumberOf3Cost, self.NumberOf4Cost, \\\n",
        "                self.NumberOf5Cost, self.NumberOf6Cost, self.NumberOfLands]\n",
        "        \n",
        "    #    void ResetHand(){\n",
        "    def ResetHand(self):\n",
        "        self.NumberOf1Cost = 0\n",
        "        self.NumberOf2Cost = 0\n",
        "        self.NumberOf3Cost = 0\n",
        "        self.NumberOf4Cost = 0\n",
        "        self.NumberOf5Cost = 0\n",
        "        self.NumberOf6Cost = 0\n",
        "        self.NumberOfLands = 0\n",
        "\n",
        "    def SetHand(self, Nr1Cost, Nr2Cost, Nr3Cost, Nr4Cost, Nr5Cost, Nr6Cost, NrLands):\n",
        "        self.NumberOf1Cost = Nr1Cost\n",
        "        self.NumberOf2Cost = Nr2Cost\n",
        "        self.NumberOf3Cost = Nr3Cost\n",
        "        self.NumberOf4Cost = Nr4Cost\n",
        "        self.NumberOf5Cost = Nr5Cost\n",
        "        self.NumberOf6Cost = Nr6Cost\n",
        "        self.NumberOfLands = NrLands\n",
        "\n",
        "    def PlayCard(self, card_type):\n",
        "        if (card_type == 1):\n",
        "            if (self.NumberOf1Cost > 0):\n",
        "                self.NumberOf1Cost -= 1\n",
        "                return True\n",
        "        elif (card_type == 2):\n",
        "            if (self.NumberOf2Cost > 0):\n",
        "                self.NumberOf2Cost -= 1\n",
        "                return True\n",
        "        elif (card_type == 3):\n",
        "            if (self.NumberOf3Cost > 0):\n",
        "                self.NumberOf3Cost -= 1\n",
        "                return True\n",
        "        elif (card_type == 4):\n",
        "            if (self.NumberOf4Cost > 0):\n",
        "                self.NumberOf4Cost -= 1\n",
        "                return True\n",
        "        elif (card_type == 5):\n",
        "            if (self.NumberOf5Cost > 0):\n",
        "                self.NumberOf5Cost -= 1\n",
        "                return True\n",
        "        elif (card_type == 6):\n",
        "            if (self.NumberOf6Cost > 0):\n",
        "                self.NumberOf6Cost -= 1\n",
        "                return True\n",
        "        elif (card_type == 7):\n",
        "            if (self.NumberOfLands > 0):\n",
        "                self.NumberOfLands -= 1\n",
        "                return True\n",
        "        else:\n",
        "            return False\n",
        "\n",
        "    def AddDrawnCard(self, card_type):\n",
        "        if card_type == 1:\n",
        "            self.NumberOf1Cost += 1\n",
        "        elif card_type == 2:\n",
        "            self.NumberOf2Cost += 1\n",
        "        elif card_type == 3:\n",
        "            self.NumberOf3Cost += 1\n",
        "        elif card_type == 4:\n",
        "            self.NumberOf4Cost += 1\n",
        "        elif card_type == 5:\n",
        "            self.NumberOf5Cost += 1\n",
        "        elif card_type == 6:\n",
        "            self.NumberOf6Cost += 1\n",
        "        elif card_type == 7:\n",
        "            self.NumberOfLands += 1\n"
      ],
      "execution_count": 12,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "FPXnrlnsurkK"
      },
      "source": [
        "class Deck:\n",
        "    def __init__(self):\n",
        "        self.NumberOf1Cost = 0\n",
        "        self.NumberOf2Cost = 0\n",
        "        self.NumberOf3Cost = 0\n",
        "        self.NumberOf4Cost = 0\n",
        "        self.NumberOf5Cost = 0\n",
        "        self.NumberOf6Cost = 0\n",
        "        self.NumberOfLands = 0\n",
        "\n",
        "    def SetDeck(self, number_1_cost, number_2_cost, number_3_cost,\n",
        "                number_4_cost, number_5_cost, number_6_cost,\n",
        "                number_of_lands):\n",
        "        self.NumberOf1Cost = number_1_cost\n",
        "        self.NumberOf2Cost = number_2_cost\n",
        "        self.NumberOf3Cost = number_3_cost\n",
        "        self.NumberOf4Cost = number_4_cost\n",
        "        self.NumberOf5Cost = number_5_cost\n",
        "        self.NumberOf6Cost = number_6_cost\n",
        "        self.NumberOfLands = number_of_lands\n",
        "\n",
        "    def NrOfCards(self):\n",
        "        value = self.NumberOf1Cost + \\\n",
        "                self.NumberOf2Cost + \\\n",
        "                self.NumberOf3Cost + \\\n",
        "                self.NumberOf4Cost + \\\n",
        "                self.NumberOf5Cost + \\\n",
        "                self.NumberOf6Cost + \\\n",
        "                self.NumberOfLands\n",
        "        return value\n",
        "\n",
        "    def DrawCard(self):\n",
        "        RandomIntegerBetweenOneAndDeckSize = random.randint(1, self.NrOfCards())\n",
        "        CardType = 0\n",
        "        OneCostCutoff = self.NumberOf1Cost\n",
        "        TwoCostCutoff = OneCostCutoff + self.NumberOf2Cost\n",
        "        ThreeCostCutoff = TwoCostCutoff + self.NumberOf3Cost\n",
        "        FourCostCutoff = ThreeCostCutoff + self.NumberOf4Cost\n",
        "        FiveCostCutoff = FourCostCutoff + self.NumberOf5Cost\n",
        "        SixCostCutoff = FiveCostCutoff + self.NumberOf6Cost\n",
        "        LandCutoff = SixCostCutoff + self.NumberOfLands\n",
        "\n",
        "        if (RandomIntegerBetweenOneAndDeckSize <= OneCostCutoff):\n",
        "            CardType = 1\n",
        "            self.NumberOf1Cost -= 1\n",
        "        if (OneCostCutoff < RandomIntegerBetweenOneAndDeckSize <= TwoCostCutoff):\n",
        "            CardType = 2\n",
        "            self.NumberOf2Cost -= 1\n",
        "        if (TwoCostCutoff < RandomIntegerBetweenOneAndDeckSize <= ThreeCostCutoff):\n",
        "            CardType = 3\n",
        "            self.NumberOf3Cost -= 1\n",
        "        if (ThreeCostCutoff < RandomIntegerBetweenOneAndDeckSize <= FourCostCutoff):\n",
        "            CardType = 4\n",
        "            self.NumberOf4Cost -= 1\n",
        "        if (FourCostCutoff < RandomIntegerBetweenOneAndDeckSize <= FiveCostCutoff):\n",
        "            CardType = 5\n",
        "            self.NumberOf5Cost -= 1\n",
        "        if (FiveCostCutoff < RandomIntegerBetweenOneAndDeckSize <= SixCostCutoff):\n",
        "            CardType = 6\n",
        "            self.NumberOf6Cost -= 1\n",
        "        if (SixCostCutoff < RandomIntegerBetweenOneAndDeckSize <= LandCutoff):\n",
        "            CardType = 7  # this has been changed to 7 so that other methods work with it\n",
        "            self.NumberOfLands -= 1\n",
        "        return CardType\n",
        "\n",
        "    def DrawHand(self):\n",
        "        card_arr = [0, 0, 0, 0, 0, 0, 0]\n",
        "        for i in range(1, 8):\n",
        "            card_arr[self.DrawCard() - 1] += 1\n",
        "        return card_arr\n",
        "        \n"
      ],
      "execution_count": 13,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "IDNwJLbyuxp7"
      },
      "source": [
        "#Main function\n",
        "#Create the ai layers\n",
        "#apparently softmax is a good option for multiple inputs\n",
        "#to get the actual output from the AI\n",
        "#output = np.argmax(A2.T[index])\n",
        "#which outputs the highest probability number.\n",
        "#Q learning is different though\n",
        "#examples are directly from website at https://adventuresinmachinelearning.com/reinforcement-learning-tutorial-python-keras/\n",
        "#We should implement the keras one, but I have included others, in order to understand what's going on.\n",
        "\n",
        "#With keras model it is\n",
        "\n",
        "model = keras.Sequential()\n",
        "model.add(layers.Input(shape=(19))) #input shape should be changed to 1, 19\n",
        "model.add(layers.Dense(40, activation='sigmoid'))\n",
        "model.add(layers.Dense(20, activation='sigmoid'))\n",
        "model.add(layers.Dense(7, activation='linear'))           #output shape should be changed to 7\n",
        "model.add(layers.Softmax())\n",
        "model.compile(loss='mse', optimizer='adam', metrics=['mae'])\n",
        "\n"
      ],
      "execution_count": 14,
      "outputs": []
    },
    {
      "cell_type": "code",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "wjEYx9_x8p81",
        "outputId": "7b883d19-966e-4f09-aabb-1fa5471317c3"
      },
      "source": [
        "env = MTGEnv()\n",
        "num_episodes = 10000\n",
        "\n",
        "# now execute the q learning\n",
        "y = .95\n",
        "eps = .5\n",
        "decay_factor = 0.9999\n",
        "r_avg_list = []\n",
        "totalAdvancingMovesGame = 0.0\n",
        "AIGames = 0.0\n",
        "movesPerGameThresh = 0.1\n",
        "for i in range(num_episodes):\n",
        "    s = env.reset()\n",
        "    eps *= decay_factor\n",
        "    if i % 100 == 0:\n",
        "        print(\"Episode {} of {}\".format(i + 1, num_episodes))\n",
        "    done = False\n",
        "    r_sum = 0\n",
        "    if i % 100 == 0:\n",
        "        print(\"game is: \")\n",
        "        print(i+1)\n",
        "\n",
        "    while not done:\n",
        "        if np.random.random() < eps:\n",
        "            a = np.random.randint(0, 7)\n",
        "            AIGame = False\n",
        "        else:\n",
        "            #a = np.random.randint(0, 7)\n",
        "            a = np.argmax(model.predict(np.array(s)))\n",
        "            AIGames += 1.0\n",
        "            AIGame = True\n",
        "        \n",
        "        if (a > 7 or a < 0):\n",
        "          print(\"A is out of bounds at:\")\n",
        "          print(a)\n",
        "        #if((s[0][0]) >= 3):\n",
        "        #  print(\"turn is: \")\n",
        "        #  print(s[0][0])\n",
        "        new_s, r, done, _ = env.step(a+1)\n",
        "        if (new_s[0][3]) > (s[0][3]):\n",
        "            if AIGame:\n",
        "                totalAdvancingMovesGame += 1\n",
        "            #print(\"game is: \")\n",
        "            #print(i+1)\n",
        "            #print(\"turn is: \")\n",
        "            #print(s[0][0])\n",
        "            #print(\"Ai decision is to play a \")\n",
        "            #print(a+1)\n",
        "            #print(\"state before is: \")\n",
        "            #print(s[0])\n",
        "            #print(\"state after is: \")\n",
        "            #print(new_s[0])\n",
        "        #if(s[0] >= 3):\n",
        "        #  print(\"new_s is: \")\n",
        "        #  print(new_s)\n",
        "        #print(type(new_s))\n",
        "        #print(new_s)\n",
        "        #print(new_s.shape())\n",
        "        target = r + y * np.max(model.predict(new_s))\n",
        "        #if(s >= 3):\n",
        "        #  print(\"target is: \")\n",
        "        #  print(target)\n",
        "        target_vec = model.predict(s)[0]\n",
        "        #if(s[0] >= 3):\n",
        "        #  print(\"target_vec is:\")\n",
        "        #  print(target_vec)\n",
        "        target_vec[a] = target\n",
        "        #if(s[0] >= 3):\n",
        "        #  print(\"target_vec[a] is:\")\n",
        "        #  print(target_vec[a])\n",
        "        model.fit(np.array(s), target_vec.reshape(-1, 7), epochs=1, verbose=0)\n",
        "        s = new_s\n",
        "        r_sum += r\n",
        "    r_avg_list.append(r_sum / 1000)\n",
        "    #print(totalAdvancingMovesGame)\n",
        "    if ((totalAdvancingMovesGame) / (AIGames+1)) > movesPerGameThresh:\n",
        "      print (\"Exceeded thresh of :\", movesPerGameThresh)\n",
        "      print (\"At the game\", i+1)\n",
        "      movesPerGameThresh += .01\n",
        "\n",
        "#Training\n",
        "\n",
        "#not sure if it is\n",
        "#env = gym.make(MTGEnv)\n",
        "#env = gyme.make('MTGEnv')\n",
        "#or\n",
        "#env = MTGEnv()\n",
        "#for _ in range(1000):\n",
        "    #env.render()\n",
        "#    observation = env.reset()\n",
        "#    print(observation)\n",
        "#    print(output)\n",
        "#    env.step(env.action_space.sample())#the env.action_space.sample() should be replaced with the np.argmax when predicting I believe\n",
        "#    env.close()\n",
        "    \n",
        "#prediction\n",
        "\n",
        "#for _ in range(1000):\n",
        "    #env.render()\n",
        "#    observation = env.reset()\n",
        "#    print(observation)\n",
        "#    print(output)\n",
        "#    env.step(np.argmax(...))#the env.action_space.sample() should be replaced with the np.argmax when predicting I believe\n",
        "#    env.close()"
      ],
      "execution_count": null,
      "outputs": [
        {
          "output_type": "stream",
          "text": [
            "Episode 1 of 10000\n",
            "game is: \n",
            "1\n",
            "Episode 101 of 10000\n",
            "game is: \n",
            "101\n",
            "Episode 201 of 10000\n",
            "game is: \n",
            "201\n",
            "Episode 301 of 10000\n",
            "game is: \n",
            "301\n",
            "Episode 401 of 10000\n",
            "game is: \n",
            "401\n"
          ],
          "name": "stdout"
        }
      ]
    },
    {
      "cell_type": "code",
      "metadata": {
        "id": "J1maa1_ilkZv"
      },
      "source": [
        "num_episodes = 100\n",
        "AIGames = 0\n",
        "totalAdvancingMovesGame = 0\n",
        "DamageSum = 0\n",
        "eps = 0\n",
        "for i in range(num_episodes):\n",
        "    s = env.reset()\n",
        "    eps *= decay_factor\n",
        "    if i % 100 == 0:\n",
        "        print(\"Episode {} of {}\".format(i + 1, num_episodes))\n",
        "    done = False\n",
        "    r_sum = 0\n",
        "    if i % 100 == 0:\n",
        "        print(\"game is: \")\n",
        "        print(i+1)\n",
        "\n",
        "    while not done:\n",
        "        if np.random.random() < eps:\n",
        "            a = np.random.randint(0, 7)\n",
        "            AIGame = False\n",
        "        else:\n",
        "            #a = np.random.randint(0, 7)\n",
        "            a = np.argmax(model.predict(np.array(s)))\n",
        "            AIGames += 1.0\n",
        "            AIGame = True\n",
        "        \n",
        "        if (a > 7 or a < 0):\n",
        "          print(\"A is out of bounds at:\")\n",
        "          print(a)\n",
        "        #if((s[0][0]) >= 3):\n",
        "        #  print(\"turn is: \")\n",
        "        #  print(s[0][0])\n",
        "        new_s, r, done, _ = env.step(a+1)\n",
        "        if (True):\n",
        "            if AIGame:\n",
        "                totalAdvancingMovesGame += 1\n",
        "                DamageSum += (new_s[0][3])\n",
        "            print(\"game is: \")\n",
        "            print(i+1)\n",
        "            print(\"turn is: \")\n",
        "            print(s[0][0])\n",
        "            print(\"Ai decision is to play a \")\n",
        "            print(a+1)\n",
        "            print(\"state before is: \")\n",
        "            print(s[0])\n",
        "            print(\"state after is: \")\n",
        "            print(new_s[0])\n",
        "    if True:\n",
        "          print (\"At thresh of :\", (totalAdvancingMovesGame) / (i+1))\n",
        "          print (\"At the game\", i+1)\n",
        "          #movesPerGameThresh += .01\n",
        "print(\"DamageSum is\", DamageSum)"
      ],
      "execution_count": null,
      "outputs": []
    }
  ]
}